name: Build and Deploy
on:
   push:
      branches: [main, master]
permissions:
   contents: write
jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - name: Build
           run: |
              npm install
              npm run build
           env:
              VITE_GITHUB_TOKEN: ${{ secrets.VITE_GITHUB_TOKEN }}
         - name: Deploy
           uses: JamesIves/github-pages-deploy-action@v4
           with:
              branch: gh-pages
              folder: dist
